/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheModelRouteImport } from './routes/the-model'
import { Route as ProofRouteImport } from './routes/proof'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as HowToStartRouteImport } from './routes/how-to-start'
import { Route as ForOemsRouteImport } from './routes/for-oems'
import { Route as CrnRouteImport } from './routes/crn'
import { Route as BookRouteImport } from './routes/book'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsPartnerpulseRouteImport } from './routes/solutions/partnerpulse'
import { Route as SolutionsIndustrialpulseRouteImport } from './routes/solutions/industrialpulse'
import { Route as SolutionsBrokerpulseRouteImport } from './routes/solutions/brokerpulse'
import { Route as LegalTermsOfServiceRouteImport } from './routes/legal/terms-of-service'
import { Route as LegalPrivacyPolicyRouteImport } from './routes/legal/privacy-policy'
import { Route as LegalCookiePolicyRouteImport } from './routes/legal/cookie-policy'
import { Route as IndustriesTechnologyProvidersRouteImport } from './routes/industries/technology-providers'
import { Route as IndustriesItSolutionProvidersRouteImport } from './routes/industries/it-solution-providers'
import { Route as CaseStudiesJfPetroleumRouteImport } from './routes/case-studies/jf-petroleum'

const TheModelRoute = TheModelRouteImport.update({
  id: '/the-model',
  path: '/the-model',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofRoute = ProofRouteImport.update({
  id: '/proof',
  path: '/proof',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToStartRoute = HowToStartRouteImport.update({
  id: '/how-to-start',
  path: '/how-to-start',
  getParentRoute: () => rootRouteImport,
} as any)
const ForOemsRoute = ForOemsRouteImport.update({
  id: '/for-oems',
  path: '/for-oems',
  getParentRoute: () => rootRouteImport,
} as any)
const CrnRoute = CrnRouteImport.update({
  id: '/crn',
  path: '/crn',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsPartnerpulseRoute = SolutionsPartnerpulseRouteImport.update({
  id: '/solutions/partnerpulse',
  path: '/solutions/partnerpulse',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndustrialpulseRoute =
  SolutionsIndustrialpulseRouteImport.update({
    id: '/solutions/industrialpulse',
    path: '/solutions/industrialpulse',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsBrokerpulseRoute = SolutionsBrokerpulseRouteImport.update({
  id: '/solutions/brokerpulse',
  path: '/solutions/brokerpulse',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsOfServiceRoute = LegalTermsOfServiceRouteImport.update({
  id: '/legal/terms-of-service',
  path: '/legal/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyPolicyRoute = LegalPrivacyPolicyRouteImport.update({
  id: '/legal/privacy-policy',
  path: '/legal/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiePolicyRoute = LegalCookiePolicyRouteImport.update({
  id: '/legal/cookie-policy',
  path: '/legal/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesTechnologyProvidersRoute =
  IndustriesTechnologyProvidersRouteImport.update({
    id: '/industries/technology-providers',
    path: '/industries/technology-providers',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustriesItSolutionProvidersRoute =
  IndustriesItSolutionProvidersRouteImport.update({
    id: '/industries/it-solution-providers',
    path: '/industries/it-solution-providers',
    getParentRoute: () => rootRouteImport,
  } as any)
const CaseStudiesJfPetroleumRoute = CaseStudiesJfPetroleumRouteImport.update({
  id: '/case-studies/jf-petroleum',
  path: '/case-studies/jf-petroleum',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/crn': typeof CrnRoute
  '/for-oems': typeof ForOemsRoute
  '/how-to-start': typeof HowToStartRoute
  '/insights': typeof InsightsRoute
  '/proof': typeof ProofRoute
  '/the-model': typeof TheModelRoute
  '/case-studies/jf-petroleum': typeof CaseStudiesJfPetroleumRoute
  '/industries/it-solution-providers': typeof IndustriesItSolutionProvidersRoute
  '/industries/technology-providers': typeof IndustriesTechnologyProvidersRoute
  '/legal/cookie-policy': typeof LegalCookiePolicyRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/solutions/brokerpulse': typeof SolutionsBrokerpulseRoute
  '/solutions/industrialpulse': typeof SolutionsIndustrialpulseRoute
  '/solutions/partnerpulse': typeof SolutionsPartnerpulseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/crn': typeof CrnRoute
  '/for-oems': typeof ForOemsRoute
  '/how-to-start': typeof HowToStartRoute
  '/insights': typeof InsightsRoute
  '/proof': typeof ProofRoute
  '/the-model': typeof TheModelRoute
  '/case-studies/jf-petroleum': typeof CaseStudiesJfPetroleumRoute
  '/industries/it-solution-providers': typeof IndustriesItSolutionProvidersRoute
  '/industries/technology-providers': typeof IndustriesTechnologyProvidersRoute
  '/legal/cookie-policy': typeof LegalCookiePolicyRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/solutions/brokerpulse': typeof SolutionsBrokerpulseRoute
  '/solutions/industrialpulse': typeof SolutionsIndustrialpulseRoute
  '/solutions/partnerpulse': typeof SolutionsPartnerpulseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/crn': typeof CrnRoute
  '/for-oems': typeof ForOemsRoute
  '/how-to-start': typeof HowToStartRoute
  '/insights': typeof InsightsRoute
  '/proof': typeof ProofRoute
  '/the-model': typeof TheModelRoute
  '/case-studies/jf-petroleum': typeof CaseStudiesJfPetroleumRoute
  '/industries/it-solution-providers': typeof IndustriesItSolutionProvidersRoute
  '/industries/technology-providers': typeof IndustriesTechnologyProvidersRoute
  '/legal/cookie-policy': typeof LegalCookiePolicyRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/solutions/brokerpulse': typeof SolutionsBrokerpulseRoute
  '/solutions/industrialpulse': typeof SolutionsIndustrialpulseRoute
  '/solutions/partnerpulse': typeof SolutionsPartnerpulseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/crn'
    | '/for-oems'
    | '/how-to-start'
    | '/insights'
    | '/proof'
    | '/the-model'
    | '/case-studies/jf-petroleum'
    | '/industries/it-solution-providers'
    | '/industries/technology-providers'
    | '/legal/cookie-policy'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/solutions/brokerpulse'
    | '/solutions/industrialpulse'
    | '/solutions/partnerpulse'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/crn'
    | '/for-oems'
    | '/how-to-start'
    | '/insights'
    | '/proof'
    | '/the-model'
    | '/case-studies/jf-petroleum'
    | '/industries/it-solution-providers'
    | '/industries/technology-providers'
    | '/legal/cookie-policy'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/solutions/brokerpulse'
    | '/solutions/industrialpulse'
    | '/solutions/partnerpulse'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/crn'
    | '/for-oems'
    | '/how-to-start'
    | '/insights'
    | '/proof'
    | '/the-model'
    | '/case-studies/jf-petroleum'
    | '/industries/it-solution-providers'
    | '/industries/technology-providers'
    | '/legal/cookie-policy'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/solutions/brokerpulse'
    | '/solutions/industrialpulse'
    | '/solutions/partnerpulse'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  CrnRoute: typeof CrnRoute
  ForOemsRoute: typeof ForOemsRoute
  HowToStartRoute: typeof HowToStartRoute
  InsightsRoute: typeof InsightsRoute
  ProofRoute: typeof ProofRoute
  TheModelRoute: typeof TheModelRoute
  CaseStudiesJfPetroleumRoute: typeof CaseStudiesJfPetroleumRoute
  IndustriesItSolutionProvidersRoute: typeof IndustriesItSolutionProvidersRoute
  IndustriesTechnologyProvidersRoute: typeof IndustriesTechnologyProvidersRoute
  LegalCookiePolicyRoute: typeof LegalCookiePolicyRoute
  LegalPrivacyPolicyRoute: typeof LegalPrivacyPolicyRoute
  LegalTermsOfServiceRoute: typeof LegalTermsOfServiceRoute
  SolutionsBrokerpulseRoute: typeof SolutionsBrokerpulseRoute
  SolutionsIndustrialpulseRoute: typeof SolutionsIndustrialpulseRoute
  SolutionsPartnerpulseRoute: typeof SolutionsPartnerpulseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/the-model': {
      id: '/the-model'
      path: '/the-model'
      fullPath: '/the-model'
      preLoaderRoute: typeof TheModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof': {
      id: '/proof'
      path: '/proof'
      fullPath: '/proof'
      preLoaderRoute: typeof ProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-start': {
      id: '/how-to-start'
      path: '/how-to-start'
      fullPath: '/how-to-start'
      preLoaderRoute: typeof HowToStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-oems': {
      id: '/for-oems'
      path: '/for-oems'
      fullPath: '/for-oems'
      preLoaderRoute: typeof ForOemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crn': {
      id: '/crn'
      path: '/crn'
      fullPath: '/crn'
      preLoaderRoute: typeof CrnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/partnerpulse': {
      id: '/solutions/partnerpulse'
      path: '/solutions/partnerpulse'
      fullPath: '/solutions/partnerpulse'
      preLoaderRoute: typeof SolutionsPartnerpulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/industrialpulse': {
      id: '/solutions/industrialpulse'
      path: '/solutions/industrialpulse'
      fullPath: '/solutions/industrialpulse'
      preLoaderRoute: typeof SolutionsIndustrialpulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/brokerpulse': {
      id: '/solutions/brokerpulse'
      path: '/solutions/brokerpulse'
      fullPath: '/solutions/brokerpulse'
      preLoaderRoute: typeof SolutionsBrokerpulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms-of-service': {
      id: '/legal/terms-of-service'
      path: '/legal/terms-of-service'
      fullPath: '/legal/terms-of-service'
      preLoaderRoute: typeof LegalTermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy-policy': {
      id: '/legal/privacy-policy'
      path: '/legal/privacy-policy'
      fullPath: '/legal/privacy-policy'
      preLoaderRoute: typeof LegalPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookie-policy': {
      id: '/legal/cookie-policy'
      path: '/legal/cookie-policy'
      fullPath: '/legal/cookie-policy'
      preLoaderRoute: typeof LegalCookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/technology-providers': {
      id: '/industries/technology-providers'
      path: '/industries/technology-providers'
      fullPath: '/industries/technology-providers'
      preLoaderRoute: typeof IndustriesTechnologyProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/it-solution-providers': {
      id: '/industries/it-solution-providers'
      path: '/industries/it-solution-providers'
      fullPath: '/industries/it-solution-providers'
      preLoaderRoute: typeof IndustriesItSolutionProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/jf-petroleum': {
      id: '/case-studies/jf-petroleum'
      path: '/case-studies/jf-petroleum'
      fullPath: '/case-studies/jf-petroleum'
      preLoaderRoute: typeof CaseStudiesJfPetroleumRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  CrnRoute: CrnRoute,
  ForOemsRoute: ForOemsRoute,
  HowToStartRoute: HowToStartRoute,
  InsightsRoute: InsightsRoute,
  ProofRoute: ProofRoute,
  TheModelRoute: TheModelRoute,
  CaseStudiesJfPetroleumRoute: CaseStudiesJfPetroleumRoute,
  IndustriesItSolutionProvidersRoute: IndustriesItSolutionProvidersRoute,
  IndustriesTechnologyProvidersRoute: IndustriesTechnologyProvidersRoute,
  LegalCookiePolicyRoute: LegalCookiePolicyRoute,
  LegalPrivacyPolicyRoute: LegalPrivacyPolicyRoute,
  LegalTermsOfServiceRoute: LegalTermsOfServiceRoute,
  SolutionsBrokerpulseRoute: SolutionsBrokerpulseRoute,
  SolutionsIndustrialpulseRoute: SolutionsIndustrialpulseRoute,
  SolutionsPartnerpulseRoute: SolutionsPartnerpulseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
